export const ADD_INGRED = 'ADD_INGRED';
export const REMOVE_INGRED = 'REMOVE_INGRED';
export const SET_INGRED = 'SET_INGRED';
export const INGRED_FAILED = 'INGRED_FAILED';

export const BURGER_PRICE_UPDATE = 'BURGER_PRICE_UPDATE';
export const BURGER_PURCHASE_START = 'BURGER_PURCHASE_START';
export const BURGER_PURCHASE_SUCCESS = 'BURGER_PURCHASE_SUCCESS';
export const BURGER_PURCHASE_FAIL = 'BURGER_PURCHASE_FAIL';

export const BUILDING_RESET = "BUILDING_RESET";

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';